version: '3.5'
services:
  nginx-app:
    image: nginx:latest
    container_name: mynginx01
    ports:
      - '7000:80'
    restart: unless-stopped
    networks:
      - internet
      - appnet

  app-db:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    networks:
      - appnet
    environment:
      - 'MYSQL_PASSWORD=mypassword'

  app-postgres:
    image: postgres:latest
    container_name: postgredb
    restart: unless-stopped
    networks:
      - appnet

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge
